<?php

require_once dirname(__FILE__) . '/../../../../fw/classes/Objeto.php';

/**
 * Test class for Objeto.
 * Generated by PHPUnit on 2012-06-21 at 13:44:23.
 */
class ObjetoTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Objeto
	 */
	protected $object;
	
	protected $default_fixture;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$Sesion = $this->getMock('Sesion');
		$this->object = new Objeto($Sesion);
		
		$this->default_fixture = array(
			'id' => 1,
			'codigo' => 'COD',
			'glosa' => 'Codigo de prueba'
		);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Objeto::Edit
	 * @todo Implement testEdit().
	 */
	public function testEdit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Objeto::Load
	 * @todo Implement testLoad().
	 */
	public function testLoad() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Objeto::Write
	 * @todo Implement testWrite().
	 */
	public function testWrite() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Objeto::Loaded
	 * @todo Implement testLoaded().
	 */
	public function testLoaded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SolicitudAdelanto::Fill
	 */
	public function testFillCompleto() {
		$this->object->editable_fields = array_keys($this->default_fixture);
		$this->object->Fill($this->default_fixture);
		
		$this->assertEquals($this->default_fixture, $this->object->fields);
	}
	
	/**
	 * @covers SolicitudAdelanto::Fill
	 */
	public function testFillInvalido() {
		$params = array(
			'campo_invalido' => 'hola',
			'otro_mas' => 'hola'
		);
		$this->object->Fill($params);
		
		$this->assertEmpty($this->object->fields);
	}
	
	/**
	 * @covers SolicitudAdelanto::Fill
	 */
	public function testFillConEdicion() {
		$this->object->editable_fields = array_keys($this->default_fixture);
		$this->object->Fill($this->default_fixture, true);
		
		$cambios_pendientes = array_fill_keys(array_keys($this->default_fixture), 1);
		
		$this->assertEquals($cambios_pendientes, $this->object->changes);
	}

	/**
	 * @covers Objeto::EditarTodos
	 * @todo Implement testEditarTodos().
	 */
	public function testEditarTodos() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Objeto::NoEditar
	 * @todo Implement testNoEditar().
	 */
	public function testNoEditar() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Objeto::Delete
	 * @todo Implement testDelete().
	 */
	public function testDelete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
