source 'http://rubygems.org'

gem 'capistrano'
gem 'rvm-capistrano'
gem 'railsless-deploy'
gem 'aws-sdk', '< 2'
gem 'capistrano_colors'
gem 'colorize'
gem 'capistrano-notifier'
gem 'capistrano-multiconfig'
gem 'rspec'
gem 'capybara'
gem 'launchy'
