source 'http://rubygems.org'

gem 'capistrano'
gem 'rvm-capistrano'
gem 'railsless-deploy'
gem 'aws-sdk'
gem 'capistrano_colors'
gem 'capistrano-notifier'
gem 'capistrano-multiconfig'
gem 'rspec'
gem 'capybara'
gem 'launchy'
