#!/bin/bash
canonicalize() {
	NAME="$1"
	if [ -f "$NAME" ]
	then
		DIR=$(dirname -- "$NAME")
		NAME=$(cd -P "$DIR" && pwd -P)/$(basename -- "$NAME")
	fi
	while [ -h "$NAME" ]; do
		DIR=$(dirname -- "$NAME")
		SYM=$(readlink "$NAME")
		NAME=$(cd "$DIR" && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
	done
	echo "$NAME"
}

DESCRIPTION=$1
DEBUG=""

if [ "$2" == "--debug" ]
then
	DEBUG="$2"
fi

CONSOLE=$(dirname -- "$(canonicalize "$0")")

exec php -q "$CONSOLE"/console.php --script=create_migration --data="{\"description\":\"$DESCRIPTION\"}" "$DEBUG"
