source 'https://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
 

gem 'jquery-rails'

group :development, :test do
	gem 'rspec'
	  gem 'rspec-rails'
  gem 'capybara'
  	gem 'savon'
     gem 'cucumber-rails',:require=>false

end
 